//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Km.Toi.Template {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Km.Toi.Template.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   引数 &quot;{0}&quot; には null 、空文字または空白文字のみの値を使用できません。  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArgumentIsNullOrWhitespace {
            get {
                return ResourceManager.GetString("ArgumentIsNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたブロック名がは設定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BlockNameNotFound {
            get {
                return ResourceManager.GetString("BlockNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメーターの数が多すぎるため自動的にパラメーター名を作成できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CantCreateAutoParameterTooManyParameter {
            get {
                return ResourceManager.GetString("CantCreateAutoParameterTooManyParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたブロック名は既に設定されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DuplicateBlockName {
            get {
                return ResourceManager.GetString("DuplicateBlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQLテンプレートの処理中に例外が発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GeneralErrorMessage {
            get {
                return ResourceManager.GetString("GeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメーターモデルクラスはパブリックである必要があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelIsMustBePublic {
            get {
                return ResourceManager.GetString("ModelIsMustBePublic", resourceCulture);
            }
        }
    }
}
