using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Km.Toi.EntityFramework.Test.Model
{
    public static class NorthwindData
    {


        public static void CreateProducts(NorthwindContext context)
        {
            context.Database.ExecuteSqlCommand("DELETE FROM PRODUCTS");
            context.Products.Add(new Product() { ProductID = 1, ProductName = "Chai", SupplierID = 1, CategoryID = 1, QuantityPerUnit = "10 boxes x 20 bags", UnitPrice = 18m, UnitsInStock = 39, UnitsOnOrder = 0, ReorderLevel = 10, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 2, ProductName = "Chang", SupplierID = 1, CategoryID = 1, QuantityPerUnit = "24 - 12 oz bottles", UnitPrice = 19m, UnitsInStock = 17, UnitsOnOrder = 40, ReorderLevel = 25, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 3, ProductName = "Aniseed Syrup", SupplierID = 1, CategoryID = 2, QuantityPerUnit = "12 - 550 ml bottles", UnitPrice = 10m, UnitsInStock = 13, UnitsOnOrder = 70, ReorderLevel = 25, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 4, ProductName = "Chef Anton's Cajun Seasoning", SupplierID = 2, CategoryID = 2, QuantityPerUnit = "48 - 6 oz jars", UnitPrice = 22m, UnitsInStock = 53, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 5, ProductName = "Chef Anton's Gumbo Mix", SupplierID = 2, CategoryID = 2, QuantityPerUnit = "36 boxes", UnitPrice = 21.35m, UnitsInStock = 0, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = true });
            context.Products.Add(new Product() { ProductID = 6, ProductName = "Grandma's Boysenberry Spread", SupplierID = 3, CategoryID = 2, QuantityPerUnit = "12 - 8 oz jars", UnitPrice = 25m, UnitsInStock = 120, UnitsOnOrder = 0, ReorderLevel = 25, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 7, ProductName = "Uncle Bob's Organic Dried Pears", SupplierID = 3, CategoryID = 7, QuantityPerUnit = "12 - 1 lb pkgs.", UnitPrice = 30m, UnitsInStock = 15, UnitsOnOrder = 0, ReorderLevel = 10, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 8, ProductName = "Northwoods Cranberry Sauce", SupplierID = 3, CategoryID = 2, QuantityPerUnit = "12 - 12 oz jars", UnitPrice = 40m, UnitsInStock = 6, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 9, ProductName = "Mishi Kobe Niku", SupplierID = 4, CategoryID = 6, QuantityPerUnit = "18 - 500 g pkgs.", UnitPrice = 97m, UnitsInStock = 29, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = true });
            context.Products.Add(new Product() { ProductID = 10, ProductName = "Ikura", SupplierID = 4, CategoryID = 8, QuantityPerUnit = "12 - 200 ml jars", UnitPrice = 31m, UnitsInStock = 31, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 11, ProductName = "Queso Cabrales", SupplierID = 5, CategoryID = 4, QuantityPerUnit = "1 kg pkg.", UnitPrice = 21m, UnitsInStock = 22, UnitsOnOrder = 30, ReorderLevel = 30, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 12, ProductName = "Queso Manchego La Pastora", SupplierID = 5, CategoryID = 4, QuantityPerUnit = "10 - 500 g pkgs.", UnitPrice = 38m, UnitsInStock = 86, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 13, ProductName = "Konbu", SupplierID = 6, CategoryID = 8, QuantityPerUnit = "2 kg box", UnitPrice = 6m, UnitsInStock = 24, UnitsOnOrder = 0, ReorderLevel = 5, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 14, ProductName = "Tofu", SupplierID = 6, CategoryID = 7, QuantityPerUnit = "40 - 100 g pkgs.", UnitPrice = 23.25m, UnitsInStock = 35, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 15, ProductName = "Genen Shouyu", SupplierID = 6, CategoryID = 2, QuantityPerUnit = "24 - 250 ml bottles", UnitPrice = 15.5m, UnitsInStock = 39, UnitsOnOrder = 0, ReorderLevel = 5, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 16, ProductName = "Pavlova", SupplierID = 7, CategoryID = 3, QuantityPerUnit = "32 - 500 g boxes", UnitPrice = 17.45m, UnitsInStock = 29, UnitsOnOrder = 0, ReorderLevel = 10, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 17, ProductName = "Alice Mutton", SupplierID = 7, CategoryID = 6, QuantityPerUnit = "20 - 1 kg tins", UnitPrice = 39m, UnitsInStock = 0, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = true });
            context.Products.Add(new Product() { ProductID = 18, ProductName = "Carnarvon Tigers", SupplierID = 7, CategoryID = 8, QuantityPerUnit = "16 kg pkg.", UnitPrice = 62.5m, UnitsInStock = 42, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 19, ProductName = "Teatime Chocolate Biscuits", SupplierID = 8, CategoryID = 3, QuantityPerUnit = "10 boxes x 12 pieces", UnitPrice = 9.2m, UnitsInStock = 25, UnitsOnOrder = 0, ReorderLevel = 5, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 20, ProductName = "Sir Rodney's Marmalade", SupplierID = 8, CategoryID = 3, QuantityPerUnit = "30 gift boxes", UnitPrice = 81m, UnitsInStock = 40, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 21, ProductName = "Sir Rodney's Scones", SupplierID = 8, CategoryID = 3, QuantityPerUnit = "24 pkgs. x 4 pieces", UnitPrice = 10m, UnitsInStock = 3, UnitsOnOrder = 40, ReorderLevel = 5, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 22, ProductName = "Gustaf's Knackebrod", SupplierID = 9, CategoryID = 5, QuantityPerUnit = "24 - 500 g pkgs.", UnitPrice = 21m, UnitsInStock = 104, UnitsOnOrder = 0, ReorderLevel = 25, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 23, ProductName = "Tunnbrod", SupplierID = 9, CategoryID = 5, QuantityPerUnit = "12 - 250 g pkgs.", UnitPrice = 9m, UnitsInStock = 61, UnitsOnOrder = 0, ReorderLevel = 25, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 24, ProductName = "Guarana Fantastica", SupplierID = 10, CategoryID = 1, QuantityPerUnit = "12 - 355 ml cans", UnitPrice = 4.5m, UnitsInStock = 20, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = true });
            context.Products.Add(new Product() { ProductID = 25, ProductName = "NuNuCa Nus-Nougat-Creme", SupplierID = 11, CategoryID = 3, QuantityPerUnit = "20 - 450 g glasses", UnitPrice = 14m, UnitsInStock = 76, UnitsOnOrder = 0, ReorderLevel = 30, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 26, ProductName = "Gumbar Gummibarchen", SupplierID = 11, CategoryID = 3, QuantityPerUnit = "100 - 250 g bags", UnitPrice = 31.23m, UnitsInStock = 15, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 27, ProductName = "Schoggi Schokolade", SupplierID = 11, CategoryID = 3, QuantityPerUnit = "100 - 100 g pieces", UnitPrice = 43.9m, UnitsInStock = 49, UnitsOnOrder = 0, ReorderLevel = 30, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 28, ProductName = "Rossle Sauerkraut", SupplierID = 12, CategoryID = 7, QuantityPerUnit = "25 - 825 g cans", UnitPrice = 45.6m, UnitsInStock = 26, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = true });
            context.Products.Add(new Product() { ProductID = 29, ProductName = "Thuringer Rostbratwurst", SupplierID = 12, CategoryID = 6, QuantityPerUnit = "50 bags x 30 sausgs.", UnitPrice = 123.79m, UnitsInStock = 0, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = true });
            context.Products.Add(new Product() { ProductID = 30, ProductName = "Nord-Ost Matjeshering", SupplierID = 13, CategoryID = 8, QuantityPerUnit = "10 - 200 g glasses", UnitPrice = 25.89m, UnitsInStock = 10, UnitsOnOrder = 0, ReorderLevel = 15, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 31, ProductName = "Gorgonzola Telino", SupplierID = 14, CategoryID = 4, QuantityPerUnit = "12 - 100 g pkgs", UnitPrice = 12.5m, UnitsInStock = 0, UnitsOnOrder = 70, ReorderLevel = 20, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 32, ProductName = "Mascarpone Fabioli", SupplierID = 14, CategoryID = 4, QuantityPerUnit = "24 - 200 g pkgs.", UnitPrice = 32m, UnitsInStock = 9, UnitsOnOrder = 40, ReorderLevel = 25, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 33, ProductName = "Geitost", SupplierID = 15, CategoryID = 4, QuantityPerUnit = "500 g", UnitPrice = 2.5m, UnitsInStock = 112, UnitsOnOrder = 0, ReorderLevel = 20, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 34, ProductName = "Sasquatch Ale", SupplierID = 16, CategoryID = 1, QuantityPerUnit = "24 - 12 oz bottles", UnitPrice = 14m, UnitsInStock = 111, UnitsOnOrder = 0, ReorderLevel = 15, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 35, ProductName = "Steeleye Stout", SupplierID = 16, CategoryID = 1, QuantityPerUnit = "24 - 12 oz bottles", UnitPrice = 18m, UnitsInStock = 20, UnitsOnOrder = 0, ReorderLevel = 15, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 36, ProductName = "Inlagd Sill", SupplierID = 17, CategoryID = 8, QuantityPerUnit = "24 - 250 g  jars", UnitPrice = 19m, UnitsInStock = 112, UnitsOnOrder = 0, ReorderLevel = 20, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 37, ProductName = "Gravad lax", SupplierID = 17, CategoryID = 8, QuantityPerUnit = "12 - 500 g pkgs.", UnitPrice = 26m, UnitsInStock = 11, UnitsOnOrder = 50, ReorderLevel = 25, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 38, ProductName = "Cote de Blaye", SupplierID = 18, CategoryID = 1, QuantityPerUnit = "12 - 75 cl bottles", UnitPrice = 263.5m, UnitsInStock = 17, UnitsOnOrder = 0, ReorderLevel = 15, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 39, ProductName = "Chartreuse verte", SupplierID = 18, CategoryID = 1, QuantityPerUnit = "750 cc per bottle", UnitPrice = 18m, UnitsInStock = 69, UnitsOnOrder = 0, ReorderLevel = 5, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 40, ProductName = "Boston Crab Meat", SupplierID = 19, CategoryID = 8, QuantityPerUnit = "24 - 4 oz tins", UnitPrice = 18.4m, UnitsInStock = 123, UnitsOnOrder = 0, ReorderLevel = 30, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 41, ProductName = "Jack's New England Clam Chowder", SupplierID = 19, CategoryID = 8, QuantityPerUnit = "12 - 12 oz cans", UnitPrice = 9.65m, UnitsInStock = 85, UnitsOnOrder = 0, ReorderLevel = 10, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 42, ProductName = "Singaporean Hokkien Fried Mee", SupplierID = 20, CategoryID = 5, QuantityPerUnit = "32 - 1 kg pkgs.", UnitPrice = 14m, UnitsInStock = 26, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = true });
            context.Products.Add(new Product() { ProductID = 43, ProductName = "Ipoh Coffee", SupplierID = 20, CategoryID = 1, QuantityPerUnit = "16 - 500 g tins", UnitPrice = 46m, UnitsInStock = 17, UnitsOnOrder = 10, ReorderLevel = 25, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 44, ProductName = "Gula Malacca", SupplierID = 20, CategoryID = 2, QuantityPerUnit = "20 - 2 kg bags", UnitPrice = 19.45m, UnitsInStock = 27, UnitsOnOrder = 0, ReorderLevel = 15, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 45, ProductName = "Rogede sild", SupplierID = 21, CategoryID = 8, QuantityPerUnit = "1k pkg.", UnitPrice = 9.5m, UnitsInStock = 5, UnitsOnOrder = 70, ReorderLevel = 15, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 46, ProductName = "Spegesild", SupplierID = 21, CategoryID = 8, QuantityPerUnit = "4 - 450 g glasses", UnitPrice = 12m, UnitsInStock = 95, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 47, ProductName = "Zaanse koeken", SupplierID = 22, CategoryID = 3, QuantityPerUnit = "10 - 4 oz boxes", UnitPrice = 9.5m, UnitsInStock = 36, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 48, ProductName = "Chocolade", SupplierID = 22, CategoryID = 3, QuantityPerUnit = "10 pkgs.", UnitPrice = 12.75m, UnitsInStock = 15, UnitsOnOrder = 70, ReorderLevel = 25, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 49, ProductName = "Maxilaku", SupplierID = 23, CategoryID = 3, QuantityPerUnit = "24 - 50 g pkgs.", UnitPrice = 20m, UnitsInStock = 10, UnitsOnOrder = 60, ReorderLevel = 15, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 50, ProductName = "Valkoinen suklaa", SupplierID = 23, CategoryID = 3, QuantityPerUnit = "12 - 100 g bars", UnitPrice = 16.25m, UnitsInStock = 65, UnitsOnOrder = 0, ReorderLevel = 30, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 51, ProductName = "Manjimup Dried Apples", SupplierID = 24, CategoryID = 7, QuantityPerUnit = "50 - 300 g pkgs.", UnitPrice = 53m, UnitsInStock = 20, UnitsOnOrder = 0, ReorderLevel = 10, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 52, ProductName = "Filo Mix", SupplierID = 24, CategoryID = 5, QuantityPerUnit = "16 - 2 kg boxes", UnitPrice = 7m, UnitsInStock = 38, UnitsOnOrder = 0, ReorderLevel = 25, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 53, ProductName = "Perth Pasties", SupplierID = 24, CategoryID = 6, QuantityPerUnit = "48 pieces", UnitPrice = 32.8m, UnitsInStock = 0, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = true });
            context.Products.Add(new Product() { ProductID = 54, ProductName = "Tourtiere", SupplierID = 25, CategoryID = 6, QuantityPerUnit = "16 pies", UnitPrice = 7.45m, UnitsInStock = 21, UnitsOnOrder = 0, ReorderLevel = 10, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 55, ProductName = "Pate chinois", SupplierID = 25, CategoryID = 6, QuantityPerUnit = "24 boxes x 2 pies", UnitPrice = 24m, UnitsInStock = 115, UnitsOnOrder = 0, ReorderLevel = 20, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 56, ProductName = "Gnocchi di nonna Alice", SupplierID = 26, CategoryID = 5, QuantityPerUnit = "24 - 250 g pkgs.", UnitPrice = 38m, UnitsInStock = 21, UnitsOnOrder = 10, ReorderLevel = 30, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 57, ProductName = "Ravioli Angelo", SupplierID = 26, CategoryID = 5, QuantityPerUnit = "24 - 250 g pkgs.", UnitPrice = 19.5m, UnitsInStock = 36, UnitsOnOrder = 0, ReorderLevel = 20, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 58, ProductName = "Escargots de Bourgogne", SupplierID = 27, CategoryID = 8, QuantityPerUnit = "24 pieces", UnitPrice = 13.25m, UnitsInStock = 62, UnitsOnOrder = 0, ReorderLevel = 20, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 59, ProductName = "Raclette Courdavault", SupplierID = 28, CategoryID = 4, QuantityPerUnit = "5 kg pkg.", UnitPrice = 55m, UnitsInStock = 79, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 60, ProductName = "Camembert Pierrot", SupplierID = 28, CategoryID = 4, QuantityPerUnit = "15 - 300 g rounds", UnitPrice = 34m, UnitsInStock = 19, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 61, ProductName = "Sirop d'erable", SupplierID = 29, CategoryID = 2, QuantityPerUnit = "24 - 500 ml bottles", UnitPrice = 28.5m, UnitsInStock = 113, UnitsOnOrder = 0, ReorderLevel = 25, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 62, ProductName = "Tarte au sucre", SupplierID = 29, CategoryID = 3, QuantityPerUnit = "48 pies", UnitPrice = 49.3m, UnitsInStock = 17, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 63, ProductName = "Vegie-spread", SupplierID = 7, CategoryID = 2, QuantityPerUnit = "15 - 625 g jars", UnitPrice = 43.9m, UnitsInStock = 24, UnitsOnOrder = 0, ReorderLevel = 5, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 64, ProductName = "Wimmers gute Semmelknodel", SupplierID = 12, CategoryID = 5, QuantityPerUnit = "20 bags x 4 pieces", UnitPrice = 33.25m, UnitsInStock = 22, UnitsOnOrder = 80, ReorderLevel = 30, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 65, ProductName = "Louisiana Fiery Hot Pepper Sauce", SupplierID = 2, CategoryID = 2, QuantityPerUnit = "32 - 8 oz bottles", UnitPrice = 21.05m, UnitsInStock = 76, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 66, ProductName = "Louisiana Hot Spiced Okra", SupplierID = 2, CategoryID = 2, QuantityPerUnit = "24 - 8 oz jars", UnitPrice = 17m, UnitsInStock = 4, UnitsOnOrder = 100, ReorderLevel = 20, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 67, ProductName = "Laughing Lumberjack Lager", SupplierID = 16, CategoryID = 1, QuantityPerUnit = "24 - 12 oz bottles", UnitPrice = 14m, UnitsInStock = 52, UnitsOnOrder = 0, ReorderLevel = 10, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 68, ProductName = "Scottish Longbreads", SupplierID = 8, CategoryID = 3, QuantityPerUnit = "10 boxes x 8 pieces", UnitPrice = 12.5m, UnitsInStock = 6, UnitsOnOrder = 10, ReorderLevel = 15, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 69, ProductName = "Gudbrandsdalsost", SupplierID = 15, CategoryID = 4, QuantityPerUnit = "10 kg pkg.", UnitPrice = 36m, UnitsInStock = 26, UnitsOnOrder = 0, ReorderLevel = 15, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 70, ProductName = "Outback Lager", SupplierID = 7, CategoryID = 1, QuantityPerUnit = "24 - 355 ml bottles", UnitPrice = 15m, UnitsInStock = 15, UnitsOnOrder = 10, ReorderLevel = 30, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 71, ProductName = "Flotemysost", SupplierID = 15, CategoryID = 4, QuantityPerUnit = "10 - 500 g pkgs.", UnitPrice = 21.5m, UnitsInStock = 26, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 72, ProductName = "Mozzarella di Giovanni", SupplierID = 14, CategoryID = 4, QuantityPerUnit = "24 - 200 g pkgs.", UnitPrice = 34.8m, UnitsInStock = 14, UnitsOnOrder = 0, ReorderLevel = 0, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 73, ProductName = "Rod Kaviar", SupplierID = 17, CategoryID = 8, QuantityPerUnit = "24 - 150 g jars", UnitPrice = 15m, UnitsInStock = 101, UnitsOnOrder = 0, ReorderLevel = 5, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 74, ProductName = "Longlife Tofu", SupplierID = 4, CategoryID = 7, QuantityPerUnit = "5 kg pkg.", UnitPrice = 10m, UnitsInStock = 4, UnitsOnOrder = 20, ReorderLevel = 5, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 75, ProductName = "Rhonbrau Klosterbier", SupplierID = 12, CategoryID = 1, QuantityPerUnit = "24 - 0.5 l bottles", UnitPrice = 7.75m, UnitsInStock = 125, UnitsOnOrder = 0, ReorderLevel = 25, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 76, ProductName = "Lakkalikoori", SupplierID = 23, CategoryID = 1, QuantityPerUnit = "500 ml", UnitPrice = 18m, UnitsInStock = 57, UnitsOnOrder = 0, ReorderLevel = 20, Discontinued = false });
            context.Products.Add(new Product() { ProductID = 77, ProductName = "Original Frankfurter grune Sose", SupplierID = 12, CategoryID = 2, QuantityPerUnit = "12 boxes", UnitPrice = 13m, UnitsInStock = 32, UnitsOnOrder = 0, ReorderLevel = 15, Discontinued = false });
            context.SaveChanges();
        }

    }
}
